#!/bin/bash

git clone https://github.com/libjxl/libjxl.git --recursive --shallow-submodules

cd libjxl
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_DEVTOOLS=ON -G Ninja ..
if ninja ssimulacra2
then
  strip tools/ssimulacra2
  cd ../..
  cp libjxl/build/tools/ssimulacra2 .
else
  echo "Build problem. Check for missing dependencies?"
fi