#!/bin/bash

mkdir build
cd build
cmake ../src -G Ninja

if ninja ssimulacra2
then
  strip ssimulacra2
  cd ..
  cp build/ssimulacra2 .
else
  echo "Build problem. Check for missing dependencies?"
  echo "Try installing dependencies:"
  echo "   sudo apt install build-essential libhwy-dev liblcms2-dev libjpeg62-turbo-dev libpng-dev cmake ninja-build"

fi